---
title: "R Notebook"
output: html_notebook
---

```{r}
pacman::p_load(tidyverse,
               faux,
               broom.mixed,
               afex,
               lme4,
               furrr)
```

```{r}
# set up the custom data simulation function
my_sim_data <- function(
  n_subj      = 100,   # number of subjects
  n_ingroup  =  25,   # number of ingroup stimuli
  n_outgroup =  25,   # number of outgroup stimuli
  beta_0     = 800,   # grand mean
  beta_1     =  0,   # effect of category
  omega_0    =  200,   # by-item random intercept sd
  tau_0      = 100,   # by-subject random intercept sd
  tau_1      =  40,   # by-subject random slope sd
  rho        = 0.2,   # correlation between intercept and slope
  sigma      = 200) { # residual (standard deviation)
  
  # simulate a sample of items
  items <- data.frame(
    item_id = seq_len(n_ingroup + n_outgroup),
    category = rep(c("ingroup", "outgroup"), c(n_ingroup, n_outgroup)),
    X_i = rep(c(-0.5, 0.5), c(n_ingroup, n_outgroup)),
    O_0i = rnorm(n = n_ingroup + n_outgroup, mean = 0, sd = omega_0)
  )

  # simulate a sample of subjects
  subjects <- faux::rnorm_multi(
    n = n_subj, mu = 0, sd = c(tau_0, tau_1), r = rho, 
    varnames = c("T_0s", "T_1s")
  )
  subjects$subj_id <- 1:n_subj
  
  # cross subject and item IDs 
  crossing(subjects, items)  %>%
    mutate(
      e_si = rnorm(nrow(.), mean = 0, sd = sigma),
      RT = beta_0 + T_0s + O_0i + (beta_1 + T_1s) * X_i + e_si
    ) %>%
    select(subj_id, item_id, category, X_i, RT)
}
```

```{r}
stimVars <- seq(from=0,to=300,by=25)
stimVarsL <- length(stimVars)
FPdf <- matrix(ncol=4,nrow=stimVarsL)

stimRvsNo <- function(
    stimVar = 0
){
df <- my_sim_data(omega_0 = stimVar)
stimR <- lmer(RT ~ 1 + X_i + (1 | item_id) + (1 + X_i | subj_id),
                data = df)

stimNo <- lmer(RT ~ 1 + X_i + (1 + X_i | subj_id),
                data = df)

subF <- lmer(RT ~ 1 + X_i + ( 1 | subj_id),
                data = df)

c(as.numeric(summary(stimNo)$coefficients[2,"Pr(>|t|)"] < .05),
  as.numeric(summary(stimR)$coefficients[2,"Pr(>|t|)"]< .05),
  as.numeric(summary(subF)$coefficients[2,"Pr(>|t|)"]< .05)
  )
}

for(i in 1:stimVarsL){

reps <- 500
# Set a "plan" for how the code should run.
plan(multisession, workers = 4)
FP <- future_map(1:reps, ~stimRvsNo(stimVar = stimVars[i]), .options = furrr_options(seed = T))
FP <- do.call(rbind, FP)
FPdf[i,] <- c(stimVars[i], colMeans(FP))

}
```

```{r}
colnames(FPdf) <- c("Omega0","NoStimR","StimR","NoStimRSubF")
FPdf <- as.data.frame(FPdf)
FPdflong <- pivot_longer(FPdf, values_to = "FP", names_to = "Type", cols = -Omega0)
```

```{r}
ggplot(FPdflong, aes(x=Omega0,color=Type,y=FP)) + geom_line() + xlab("Stimulus-Level Variation") + ylab("False Positive Percentage") + scale_color_discrete(labels = c("RSub+Random Slope","RSub+Fixed Slope","RStim and RSub+Fixed Slope")) + geom_hline(aes(yintercept=.05), , linetype="dashed")
```

# Iterating Over Subject Slope Variance and Stimulus Intercept Variance

```{r}
stimVars <- seq(from=0,to=300,by=25)
stimVarsL <- length(stimVars)
subSVars <- seq(from=0,to=250,by=50)
subSVarsL <- length(subSVars)
FPdf2 <- matrix(ncol=5,nrow=stimVarsL*subSVarsL)

stimRvsNo <- function(
    stimVar = 200,
    subjSlopeVar = 100,
    subjIntVar = 40,
    n_Sub = 100,
    n_StimI  =  25,
    n_StimO =  25
){
df <- my_sim_data(omega_0 = stimVar, tau_1 = subjSlopeVar)
stimR <- lmer(RT ~ 1 + X_i + (1 | item_id) + (1 + X_i | subj_id),
                data = df)

stimNo <- lmer(RT ~ 1 + X_i + (1 + X_i | subj_id),
                data = df)

subF <- lmer(RT ~ 1 + X_i + ( 1 | subj_id),
                data = df)

c(as.numeric(summary(stimNo)$coefficients[2,"Pr(>|t|)"] < .05),
  as.numeric(summary(stimR)$coefficients[2,"Pr(>|t|)"]< .05),
  as.numeric(summary(subF)$coefficients[2,"Pr(>|t|)"]< .05)
  )
}

iter <- 1
for(j in 1:subSVarsL){
  for(i in 1:stimVarsL){
  
  reps <- 500
  # Set a "plan" for how the code should run.
  plan(multisession, workers = 4)
  FP <- future_map(1:reps, ~stimRvsNo(stimVar = stimVars[i], subjSlopeVar = subSVars[j]), .options = furrr_options(seed = T))
  FP <- do.call(rbind, FP)
  FPdf2[iter,] <- c(stimVars[i], subSVars[j], colMeans(FP))
  iter <- iter + 1
  
  }
}
```

```{r}
colnames(FPdf2) <- c("Omega0","Tau1","NoStimR","StimR","NoStimRSubF")
FPdf2 <- as.data.frame(FPdf2)
FPdflong2 <- pivot_longer(FPdf2, values_to = "FP", names_to = "Type", cols = -c(Omega0,Tau1))
```

```{r}
ggplot(FPdflong2, aes(x=Omega0,color=Type,y=FP)) + geom_line() + xlab("Stimulus-Level Variation") + ylab("False Positive Percentage") + scale_color_discrete(labels = c("RSub+Random Slope","RSub+Fixed Slope","RStim and RSub+Random Slope")) + geom_hline(aes(yintercept=.05), linetype="dashed") + facet_wrap(~Tau1)
```

# Iterating Over Subject N and Stimulus Intercept Variance

```{r}
stimVars <- seq(from=0,to=300,by=25)
stimVarsL <- length(stimVars)
subSsamp <- seq(from=50,to=300,by=50)
subSsampL <- length(subSsamp)
FPdf3 <- matrix(ncol=5,nrow=stimVarsL*subSsampL)

stimRvsNo <- function(
    stimVar = 200,
    subjSlopeVar = 100,
    subjIntVar = 40,
    n_Sub = 100,
    n_StimI  =  25,
    n_StimO =  25
){
df <- my_sim_data(omega_0 = stimVar, n_subj = n_Sub)
stimR <- lmer(RT ~ 1 + X_i + (1 | item_id) + (1 + X_i | subj_id),
                data = df)

stimNo <- lmer(RT ~ 1 + X_i + (1 + X_i | subj_id),
                data = df)

subF <- lmer(RT ~ 1 + X_i + ( 1 | subj_id),
                data = df)

c(as.numeric(summary(stimNo)$coefficients[2,"Pr(>|t|)"] < .05),
  as.numeric(summary(stimR)$coefficients[2,"Pr(>|t|)"]< .05),
  as.numeric(summary(subF)$coefficients[2,"Pr(>|t|)"]< .05)
  )
}

iter <- 1
for(j in 1:subSsampL){
  for(i in 1:stimVarsL){
  
  reps <- 500
  # Set a "plan" for how the code should run.
  plan(multisession, workers = 4)
  FP <- future_map(1:reps, ~stimRvsNo(stimVar = stimVars[i], n_Sub = subSsamp[j]), .options = furrr_options(seed = T))
  FP <- do.call(rbind, FP)
  FPdf3[iter,] <- c(stimVars[i], subSsamp[j], colMeans(FP))
  iter <- iter + 1
  
  }
}
```

```{r}
colnames(FPdf3) <- c("Omega0","Sub_N","NoStimR","StimR","NoStimRSubF")
FPdf3 <- as.data.frame(FPdf3)
FPdflong3 <- pivot_longer(FPdf3, values_to = "FP", names_to = "Type", cols = -c(Omega0,Sub_N))
```

```{r}
ggplot(FPdflong3, aes(x=Omega0,color=Type,y=FP)) + geom_line() + xlab("Stimulus-Level Variation") + ylab("False Positive Percentage") + scale_color_discrete(labels = c("RSub+Random Slope","RSub+Fixed Slope","RStim and RSub+Random Slope")) + geom_hline(aes(yintercept=.05), linetype="dashed") + facet_wrap(~Sub_N)
```

# Iterating Over Stimulus N and Stimulus Intercept Variance

```{r}
stimVars <- seq(from=0,to=300,by=25)
stimVarsL <- length(stimVars)
subSsamp <- seq(from=25,to=150,by=25)
subSsampL <- length(subSsamp)
FPdf4 <- matrix(ncol=5,nrow=stimVarsL*subSsampL)

stimRvsNo <- function(
    stimVar = 200,
    subjSlopeVar = 100,
    subjIntVar = 40,
    n_Sub = 100,
    n_StimI  =  25,
    n_StimO =  25
){
df <- my_sim_data(omega_0 = stimVar, n_ingroup = n_StimI, n_outgroup = n_StimO)
stimR <- lmer(RT ~ 1 + X_i + (1 | item_id) + (1 + X_i | subj_id),
                data = df)

stimNo <- lmer(RT ~ 1 + X_i + (1 + X_i | subj_id),
                data = df)

subF <- lmer(RT ~ 1 + X_i + ( 1 | subj_id),
                data = df)

c(as.numeric(summary(stimNo)$coefficients[2,"Pr(>|t|)"] < .05),
  as.numeric(summary(stimR)$coefficients[2,"Pr(>|t|)"]< .05),
  as.numeric(summary(subF)$coefficients[2,"Pr(>|t|)"]< .05)
  )
}

iter <- 1
for(j in 1:subSsampL){
  for(i in 1:stimVarsL){
  
  reps <- 500
  # Set a "plan" for how the code should run.
  plan(multisession, workers = 4)
  FP <- future_map(1:reps, ~stimRvsNo(stimVar = stimVars[i], n_StimI = subSsamp[j], n_StimO = subSsamp[j]), .options = furrr_options(seed = T))
  FP <- do.call(rbind, FP)
  FPdf4[iter,] <- c(stimVars[i], subSsamp[j], colMeans(FP))
  iter <- iter + 1
  
  }
}
```

```{r}
colnames(FPdf4) <- c("Omega0","Stim_N","NoStimR","StimR","NoStimRSubF")
FPdf4 <- as.data.frame(FPdf4)
FPdflong4 <- pivot_longer(FPdf4, values_to = "FP", names_to = "Type", cols = -c(Omega0,Stim_N))
```

```{r}
ggplot(FPdflong4, aes(x=Omega0,color=Type,y=FP)) + geom_line() + xlab("Stimulus-Level Variation") + ylab("False Positive Percentage") + scale_color_discrete(labels = c("RSub+Random Slope","RSub+Fixed Slope","RStim and RSub+Random Slope")) + geom_hline(aes(yintercept=.05), linetype="dashed") + facet_wrap(~Stim_N)
```